yellow_rect:
	$(CC) draw_rec.c glad.c -o draw_rec -lmingw32 -lSDL2main -lSDL2 -lopengl32

load_png:
	$(CC) load_png.c glad.c -o load_png -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lopengl32

load_png2:
	$(CC) load_png2.c glad.c -o load_png2 -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lopengl32